spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    url: jdbc:mysql://127.0.0.1:13306/mall?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

server.servlet.session.timeout: 10
