spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 66264276xY!
    url: jdbc:mysql://139.196.253.125:3306/mall?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  redis:
    host: 139.196.253.125
    port: 6379
    password: 66264276xY!
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
  path:
server.servlet.session.timeout: 10
server:
  port: 8181
